### ISSUE TITLE
Disabling source maps does not work

### ISSUE THREAD

**Issue by grossbart** [Meteor-Community-Packages/meteor-typescript#11]
I can't find a way to disable source maps using this package. I have disabled them in my `tsconfig.json`, but then found that it didn't change anything.

When I change meteor-typescript-compiler and set the `sourceMap` option in `optionsToExtend` to false, it works: https://github.com/Meteor-Community-Packages/meteor-typescript-compiler/blob/master/meteor-typescript-compiler.ts#L362

Is there a reason that this is hard-coded or could it just be removed and be taken from `tsconfig.json`?

**Comment by perbergland** [comment]
It seems like a natural option to be able to turn it off - I’ll try to remember to fix this next time I do a release, or if you want to create a PR for it?

**Comment by perbergland** [comment]
This has been implemented now, along with an override option via an environment variable

**Comment by grossbart** [comment]
Thanks a lot, I will give this a go next week 🙏
